export const SKILLS: Record<string, string[]> = {
  "Programming & ML": [
    "Python",
    "SQL",
    "R",
    "pandas",
    "NumPy",
    "scikit-learn",
    "PyTorch",
    "XGBoost",
    "SHAP",
  ],
  "Modeling & Experimentation": [
    "Propensity scoring",
    "A/B testing",
    "Experiment design",
    "Hypothesis testing",
    "Causal inference",
    "Ranking / recommendation",
    "Probabilistic forecasting",
    "Monte Carlo simulation",
  ],
  "Evaluation & Monitoring": [
    "Walk-forward validation",
    "Brier score",
    "Multiclass log loss",
    "Regression suites",
    "Feature drift",
    "Prediction drift",
    "Data quality validation",
  ],
  "Applied AI": [
    "LLMs / RAG",
    "LangChain",
    "Agentic workflows",
    "Multi-agent orchestration",
    "LLM evaluation",
    "Guardrails",
    "FastAPI",
    "REST APIs",
  ],
  "Data & MLOps": [
    "Spark / PySpark",
    "Databricks",
    "MLflow",
    "Production ML",
    "ETL / ELT",
    "Data warehousing",
    "Docker",
    "CI / CD",
    "GitHub Actions",
  ],
  "Databases & Cloud": [
    "Postgres",
    "Snowflake",
    "DuckDB",
    "ChromaDB",
    "AWS S3",
    "AWS EMR",
    "AWS Athena",
    "AWS SageMaker",
    "GCP Cloud Run",
  ],
};
